
export  const PRODUCT_FAILURE = "PRODUCT_FAILURE"
export  const PRODUCT_LOADING = "PRODUCT_LOADING"

// POST
export  const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"

// GET
export  const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"

export  const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS"

