
// Comman
export  const CART_FAILURE = "CART_FAILURE"
export  const CART_LOADING = "CART_LOADING"

// POST
export  const ADD_CART_SUCCESS = "ADD_CART_SUCCESS"

// GET
export  const GET_CART_SUCCESS = "GET_CART_SUCCESS"

// DELETE
export  const REMOVE_SUCCESS = "REMOVE_SUCCESS"

// PATCH
export  const PATCH_SUCCESS = "PATCH_SUCCESS"
